baseurl = "https://wwymak.github.io"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
# title = "The number mill"
canonifyurls  = true
site.Copyright = "© Wendy Mak 2023"

DefaultContentLanguage = "en"
theme = "PaperMod"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
enableEmoji = true
enableGitInfo = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]


[frontmatter]
  date = ['date', 'publishDate', 'lastmod']
  expiryDate = ['expiryDate']
  lastmod = [':git', 'lastmod', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']


[Params]
  subtitle = "Anything goes that captures my interest :) "
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  author = "Wendy Mak"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true

[Params.EditPost]
  url = "https://github.com/wwymak/wwymak.github.io/tree/main/content/"
  text = "Suggest Changes"
  appendFilePath = true

[Params.Assets]
  favicon = "avatar.png"

# [Params.ProfileMode]
#   enabled = true
#   title = "The number mill"
#   subtitle = "Thoughts, summaries around data science, software stuff, and other random bits and pieces of knowledge I come across"
#   imageUrl = "avatar.png"

[Params.HomeInfoParams]
  title = "The number mill"
  Content = "Thoughts, summaries around data science, software stuff, and other random bits and pieces of knowledge I come across"

[[Params.SocialIcons]]
  name = "github"
  url = "https://github.com/wwymak"
[[Params.SocialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/wwymak"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3


